### ISSUE TITLE
Leaflet Maps Are not Working for me. 

### ISSUE THREAD

**Issue by 0Redfeather** [msu-anthropology/indian-country#49]
Just checked out a few of the Indian Country Projects and noticed that non of the maps are showing up for me. The pop-ups and markups are good, but the map appears as white space. 

Not sure if it's limited to my computer, or if something is wrong with pulling the Leaflet map. Worked fine when I updated the points back in April/May.

**Comment by geyerbri** [comment]
This is because Mapbox got rid of their classic maps/styles/studio. You'll (whoever is doing upkeep) need to get into Mapbox to find a new style to switch these projects over to, then update the leaflet map code for the newer way of doing things. This will be true for every one of the indian-country and daea repos, I think.

For an example of an updated version (the map only, the pins are broken at the moment), you can look at my [kenya-tweet repo](https://github.com/geyerbri/kenya-tweet/blob/master/map.html).

**Comment by 0Redfeather** [comment]
Awesome, thanks! I figured it was probably something like that.

**Comment by 0Redfeather** [comment]
Got map to appear, now new code needs to be applied to other iterations
